services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.128.0
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
